### ISSUE TITLE
Remove references to webbloatscore.com

### ISSUE THREAD

**Issue by e-l-i-j-a-h** [ZSvedic/WebBS-Calculator#6]
Links referencing [webbloatscore.com](https://webbloatscore.com) should be removed now that the domain is home to a slot machine scam.

**Comment by ZSvedic** [comment]
@e-l-i-j-a-h Thanks for noticing! I have removed links from readme.md and GitHub description.

**Comment by e-l-i-j-a-h** [comment]
Haha that was quick. Appreciate it 👍
